import {
    Elevation,
    MaterialPalette,
    MaterialStyleMetrics,
} from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";
import { MaterialStyleMetrics } from "../material-1.0/material.slint";

export struct BatteryDataSlint {
    percentage: int,
    state: string,
}

export component BatteryButton inherits Rectangle {
    height: 100%;

    in property <BatteryDataSlint> battery;

    callback battery_clicked();

    HorizontalLayout {
        spacing: 4px;
        padding: 3px;
        height: 100%;

        Rectangle {
            border_radius: MaterialStyleMetrics.border_radius_28;
            elevation := Elevation {
                border_radius: parent.border_radius;
                width: 100%;
                height: 100%;
                background: transparent;
            }

            base := BaseButton {
                border_radius: parent.border_radius;
                width: 100%;

                icon: root.battery.state == "Unknown" ? @image-url("../assets/battery/battery_unknown.svg") : root.battery.state == "Empty" ? @image-url("../assets/battery/battery_alert_empty.svg") : root.battery.state == "FullyCharged" ? @image-url("../assets/battery/battery_full.svg") : root.battery.state == "Charging" ? @image-url("../assets/battery/battery_charging.svg") : root.battery.percentage <= 10 ? @image-url("../assets/battery/battery_1.svg") : root.battery.percentage <= 25 ? @image-url("../assets/battery/battery_2.svg") : root.battery.percentage <= 40 ? @image-url("../assets/battery/battery_3.svg") : root.battery.percentage <= 55 ? @image-url("../assets/battery/battery_4.svg") : root.battery.percentage <= 70 ? @image-url("../assets/battery/battery_5.svg") : root.battery.percentage <= 90 ? @image-url("../assets/battery/battery_6.svg") : @image-url("../assets/battery/battery_full.svg");

                text: root.battery.percentage + "%";
                spacing: 4px;
                icon-size: 20px;
                button_horizontal_padding: MaterialStyleMetrics.padding_8;
                icon_color: transparent;
                color: MaterialPalette.on_surface;

                clicked => {
                    root.battery_clicked();
                }
            }

            states [
                hover when base.has_hover && !base.pressed && !base.enter_pressed: {
                    elevation.level: 2;
                    elevation.background: MaterialPalette.surface_container_high;
                }
                pressed when base.pressed || base.enter_pressed: {
                    elevation.level: 1;
                    elevation.background: MaterialPalette.surface_container_highest;
                }
            ]
        }
    }
}
