import {
    Elevation,
    ScrollView,
    MaterialPalette,
    MaterialTypography,
    MaterialStyleMetrics,
    CheckBox,
    RadioButton,
    CheckState,
    VerticalDivider,
    NavigationBar,
    Dialog,
    MaterialText,
} from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";
import {
    MaterialStyleMetrics,
} from "../material-1.0/ui/styling/material_style_metrics.slint";
import {
    ConfigSlint,
} from "../shared-items.slint";
import {
    MaterialPalette,
} from "../material-1.0/ui/styling/material_palette.slint";
import { FilledButton } from "../material-1.0/material.slint";
import {
    MaterialTypography,
} from "../material-1.0/ui/styling/material_typography.slint";

import { CalendarWidget, Date } from "./widgets/calendar.slint";
import { MediaInfo, MediaPlayer } from "./widgets/media-player.slint";

export component MediaButton inherits Rectangle {
    in-out property <image> icon;
    in-out property <length> icon_size: 20px;
    in-out property <color> icon_color: MaterialPalette.on_surface;

    in-out property <length> size: 40px;
    in-out property <length> radius: MaterialStyleMetrics.border_radius_28;

    callback clicked();

    width: root.size;
    height: root.size;
    border_radius: root.radius;
    vertical-stretch: 0;

    elevation := Elevation {
        border_radius: root.border_radius;
        width: parent.width;
        height: parent.height;
        background: MaterialPalette.surface_container_highest;
    }

    base := BaseButton {
        border_radius: root.border_radius;
        width: parent.width;
        height: 100%;

        icon: root.icon;
        icon-size: root.icon_size;
        icon_color: root.icon_color;
        color: root.icon_color;

        spacing: 4px;
        button_horizontal_padding: 0px;
        button_vertical_padding: 0px;

        clicked => {
            root.clicked();
        }
    }

    states [
        hover when base.has_hover && !base.pressed && !base.enter_pressed: {
            elevation.level: 2;
            elevation.background: MaterialPalette.surface_container_high;
        }
        pressed when base.pressed || base.enter_pressed: {
            elevation.level: 1;
            elevation.background: MaterialPalette.surface_container_highest;
        }
    ]
}

export component PowerButton inherits Rectangle {
    in property <image> icon: @image-url("../assets/control_center/power.svg");
    in property <string> text: "";
    in property <length> icon-size: 42px;

    callback clicked();
    VerticalLayout {
        alignment: center;
        spacing: MaterialStyleMetrics.spacing_4;
        Rectangle {
            height: 100px;
            width: self.height;
            border_radius: MaterialStyleMetrics.border_radius_28;

            elevation_power_but := Elevation {
                border_radius: parent.border_radius;
                background: MaterialPalette.surface_container_highest;
                width: 100%;
                height: 100%;
            }

            base := BaseButton {
                border_radius: parent.border_radius;

                icon: root.icon;
                icon-size: root.icon-size;

                button_horizontal_padding: 0px;
                icon-color: transparent;
                color: MaterialPalette.on_surface;

                clicked => {
                    root.clicked();
                }
            }

            states [
                hover when base.has-hover && !base.pressed && !base.enter_pressed: {
                    elevation_power_but.level: 2;
                }
            ]
        }

        HorizontalLayout {
            alignment: center;
            Text {
                font-size: MaterialTypography.body_large.font-size;
                font-weight: MaterialTypography.body_large.font-weight;
                text: root.text;
            }
        }
    }
}

export component ControlPanel inherits Rectangle {
    in property <ConfigSlint> config;
    in property <bool> panel_visible;
    in property <string> username;
    in property <image> profileImage;
    in property <int> upTimeHours;
    in property <int> upTimeMinutes;

    in property <int> currentTimeHour;
    in property <int> currentTimeMinute;
    in property <Date> dateToday;
    in-out property <Date> calendar_selected_date;
    in-out property <int> calendar_display_month: root.dateToday.month;
    in-out property <int> calendar_display_year: root.dateToday.year;
    in-out property <int> calendar_start_column;

    // --- Media Player Properties ---
    in property <MediaInfo> mediaData;
    in property <image> mediaCover;
    in property <int> media_position_seconds: 0;
    in property <[string]> player_list: [];
    in property <string> current_player;

    pure callback month_day_count(int, int) -> int;
    pure callback month_offset(int, int) -> int;

    callback calendar_select_date(Date);
    callback calendar_month_changed(int, int);

    changed panel_visible => {
        callendar.reset_selection();
    }

    width: root.panel_visible ? 100% : 0%;
    height: root.panel_visible ? 100% : 0%;
    clip: true;
    y: 0px;

    callback shutdown();
    callback reboot();
    callback lock();
    callback suspend();

    // --- Media Player Callbacks ---
    callback set_position(int);
    callback toggle_shuffle(string);
    callback cycle_loop_status(string);
    callback media_play_pause();
    callback media_previous();
    callback media_next();
    callback select_player(string /* player_identity */);

    animate height {
        duration: 300ms * config.interaction.animation-multiplier;
        easing: ease-in-out-back;
    }
    animate width {
        duration: 250ms * config.interaction.animation-multiplier;
        easing: ease-in-out-back;
    }
    dialog := Dialog {
        x: -root.absolute_position.x;
        y: -root.absolute_position.y;
        width: root.width;
        height: root.height;

        HorizontalLayout {
            spacing: MaterialStyleMetrics.spacing_16;
            alignment: center;
            PowerButton {
                text: "Shutdown";
                icon: @image-url("../assets/control_center/power_40x40.svg");
                clicked => {
                    root.shutdown();
                }
            }

            PowerButton {
                text: "Reboot";
                icon: @image-url("../assets/control_center/reboot_40x40.svg");
                clicked => {
                    root.reboot();
                }
            }

            PowerButton {
                text: "Lock";
                icon: @image-url("../assets/control_center/lock_40x40.svg");
                clicked => {
                    root.lock();
                    dialog.close();
                }
            }

            PowerButton {
                text: "Suspend";
                icon: @image-url("../assets/control_center/suspend_40x40.svg");
                clicked => {
                    root.suspend();
                    dialog.close();
                }
            }
        }

        action_clicked(index) => {
            dialog.close();
        }

        default_action_clicked => {
            dialog.close();
        }
    }

    HorizontalLayout {
        y: 0px;
        width: 900px;
        height: 465px;
        alignment: center;
        TouchArea {
            y: 0px;
            width: 100%;
            height: 100%;

            elevation := Rectangle {
                y: 0px;
                width: 100%;
                height: 100%;

                Path {
                    width: root.panel_visible ? ((config.window.bar-height + 3px)) + 2px : 0px;
                    height: root.panel_visible ? ((config.window.bar-height + 3px)) + 1px : 0px;
                    y: 0px;
                    x: -self.width + 1px;

                    animate width, height {
                        duration: 300ms * config.interaction.animation-multiplier;
                        easing: ease-in-out-back;
                    }
                    fill: MaterialPalette.surface_container;
                    commands: "M 7 3 L 12 3 L 12 8 C 11 5 10 4 7 3";
                }

                Path {
                    width: root.panel_visible ? ((config.window.bar-height + 3px)) + 2px : 0px;
                    height: root.panel_visible ? ((config.window.bar-height + 3px)) + 1px : 0px;
                    y: 0px;
                    x: parent.width - 1px;

                    animate width, height {
                        duration: 300ms * config.interaction.animation-multiplier;
                        easing: ease-in-out-back;
                    }
                    fill: MaterialPalette.surface_container;
                    commands: "M 7 8 L 7 3 L 12 3 C 9 4 8 5 7 8";
                }

                VerticalLayout {
                    padding: MaterialStyleMetrics.padding_8;
                    VerticalLayout {
                        spacing: 0px;
                        padding: MaterialStyleMetrics.padding_14;
                        padding-bottom: MaterialStyleMetrics.padding_4;
                        NavigationBar {
                            items: [
                                {
                                    icon: @image-url("../assets/control_center/home.svg"),
                                    selected_icon: @image-url("../assets/control_center/home.svg"),
                                    text: "Home",
                                    badge: ""
                                },
                            ];
                        }
                    }

                    Rectangle {
                        height: 1px;
                        background: MaterialPalette.outline_variant;
                    }

                    mainLayout := VerticalLayout {
                        padding-top: MaterialStyleMetrics.padding_8;
                        spacing: MaterialStyleMetrics.spacing_8;

                        HorizontalLayout {
                            spacing: MaterialStyleMetrics.spacing_8;
                            HorizontalLayout {
                                spacing: MaterialStyleMetrics.spacing_8;

                                VerticalLayout {
                                    spacing: MaterialStyleMetrics.spacing_8;
                                    min-width: 265px;
                                    max-width: 265px;
                                    Elevation {
                                        level: 2;
                                        border_radius: MaterialStyleMetrics.border_radius_16;
                                        background: MaterialPalette.surface_container_high;
                                        userLayout := HorizontalLayout {
                                            padding: MaterialStyleMetrics.padding_12;
                                            padding-top: MaterialStyleMetrics.padding_24;
                                            padding-bottom: self.padding-top;
                                            spacing: MaterialStyleMetrics.spacing_16;

                                            Image {
                                                height: 82px;
                                                width: 82px;
                                                source: root.profileImage;
                                            }

                                            HorizontalLayout {
                                                VerticalLayout {
                                                    spacing: MaterialStyleMetrics.spacing_8;

                                                    alignment: center;
                                                    Text {
                                                        max-width: 80px;
                                                        text: root.username;
                                                        font-size: MaterialTypography.title_large.font-size;
                                                        font-weight: 500;
                                                        overflow: elide;
                                                    }

                                                    HorizontalLayout {
                                                        spacing: MaterialStyleMetrics.spacing_4;
                                                        padding-right: MaterialStyleMetrics.padding_10;
                                                        VerticalLayout {
                                                            alignment: center;
                                                            Image {
                                                                height: 20px;
                                                                width: 20px;
                                                                source: @image-url("../assets/control_center/uptime.svg");
                                                                colorize: MaterialPalette.on_surface_variant;
                                                            }
                                                        }

                                                        Text {
                                                            max-width: 80px;
                                                            vertical-alignment: center;
                                                            horizontal-alignment: center;
                                                            text: (root.upTimeHours < 10 ? "0" : "") + root.upTimeHours + ":" +
                                                                (root.upTimeMinutes < 10 ? "0" : "") + root.upTimeMinutes;
                                                            font-size: MaterialTypography.title_small.font_size;
                                                            font-weight: MaterialTypography.title_small.font-weight;
                                                            color: MaterialPalette.on_surface_variant;
                                                        }
                                                    }
                                                }
                                            }

                                            VerticalLayout {
                                                alignment: center;
                                                Rectangle {
                                                    height: 40px;
                                                    width: self.height + 2px;
                                                    border_radius: MaterialStyleMetrics.border_radius_28;

                                                    elevation_power_but := Elevation {
                                                        border_radius: parent.border_radius;
                                                        level: 2;
                                                        background: MaterialPalette.surface_container_highest;
                                                        width: 100%;
                                                        height: 100%;
                                                    }

                                                    base := BaseButton {
                                                        border_radius: parent.border_radius;
                                                        icon-size: 20px;
                                                        button_horizontal_padding: 0px;
                                                        icon: @image-url("../assets/control_center/power.svg");
                                                        icon-color: transparent;
                                                        color: MaterialPalette.on_surface;

                                                        clicked => {
                                                            dialog.show();
                                                        }
                                                    }

                                                    states [
                                                        hover when base.has-hover && !base.pressed && !base.enter_pressed: {
                                                            elevation_power_but.level: 3;
                                                        }
                                                    ]
                                                }
                                            }
                                        }
                                    }

                                    Elevation {
                                        level: 3;
                                        border_radius: MaterialStyleMetrics.border_radius_16;
                                        background: MaterialPalette.surface_container_high;

                                        callendar := CalendarWidget {
                                            calendar_today: root.dateToday;
                                            calendar_start_column <=> root.calendar_start_column;

                                            month_day_count(m, y) => {
                                                return root.month_day_count(m, y);
                                            }
                                            month_offset(m, y) => {
                                                return root.month_offset(m, y);
                                            }
                                        }
                                    }
                                }

                                VerticalLayout {
                                    spacing: MaterialStyleMetrics.spacing_8;

                                    Elevation {
                                        level: 2;
                                        border_radius: MaterialStyleMetrics.border_radius_16;
                                        background: MaterialPalette.surface_container_high;
                                        VerticalLayout {
                                            spacing: MaterialStyleMetrics.spacing_8;
                                            padding: MaterialStyleMetrics.padding_12;
                                            VerticalLayout {
                                                spacing: -10px;
                                                Text {
                                                    horizontal-alignment: center;
                                                    vertical-alignment: bottom;
                                                    text: (root.currentTimeHour < 10 ? "0" : "") + root.currentTimeHour + ":" + (root.currentTimeMinute < 10 ? "0" : "") + root.currentTimeMinute;
                                                    font-size: MaterialTypography.display_large.font-size * 1.3;
                                                    font-weight: 500;
                                                }

                                                Text {
                                                    vertical-alignment: top;
                                                    horizontal-alignment: center;
                                                    text: dateToday.day + "." + dateToday.month + "." + dateToday.year;
                                                    font-size: MaterialTypography.label_large.font-size;
                                                    font-weight: 500;
                                                }
                                            }

                                            NavigationBar {
                                                items: [
                                                    {
                                                        icon: @image-url("../assets/control_center/home.svg"),
                                                        selected_icon: @image-url("../assets/control_center/home.svg"),
                                                        text: "To Do someday",
                                                        badge: ""
                                                    },
                                                ];
                                            }

                                            alignment: center;
                                        }
                                    }

                                    Elevation {
                                        level: 2;
                                        border_radius: MaterialStyleMetrics.border_radius_16;
                                        background: MaterialPalette.surface_container_high;
                                        VerticalLayout {
                                            alignment: center;
                                            padding: MaterialStyleMetrics.padding_10;

                                            MediaPlayer {
                                                media_info: root.mediaData;
                                                media_cover: root.mediaCover;
                                                media_position_seconds: root.media_position_seconds;
                                                player_list: root.player_list;
                                                current_player: root.current_player;

                                                select_player(player) => { root.select_player(player); }
                                                set_position(secs) => { root.set_position(secs); }
                                                toggle_shuffle(enable) => { root.toggle_shuffle(enable); }
                                                cycle_loop_status(status) => { root.cycle_loop_status(status); }
                                                play_pause() => { root.media_play_pause(); }
                                                previous() => { root.media_previous(); }
                                                next() => { root.media_next(); }
                                            }
                                        }
                                    }
                                }
                            }

                            Elevation {
                                min-width: 265px;
                                max-width: 265px;
                                level: 2;
                                border_radius: MaterialStyleMetrics.border_radius_16;
                                background: MaterialPalette.surface_container_high;
                            }
                        }
                    }
                }

                background: MaterialPalette.surface_container;
                border-bottom-left-radius: MaterialStyleMetrics.border_radius_16;
                border-bottom-right-radius: MaterialStyleMetrics.border_radius_16;
            }
        }
    }
}
