import {
    Elevation,
    ScrollView,
    MaterialPalette,
    MaterialTypography,
    MaterialStyleMetrics,
    CheckBox,
    RadioButton,
    CheckState,
    VerticalDivider,
} from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";

export component ProfilesRow inherits Rectangle {
    height: 100%;
    in property <string> powerProfile;

    callback set_power_profile(string);

    in property <[{ name: string, icon: image}]> profiles: [
        { name: "power-saver", icon: @image-url("../assets/profiles/power_saver.svg") },
        { name: "balanced", icon: @image-url("../assets/profiles/balanced.svg") },
        { name: "performance", icon: @image-url("../assets/profiles/performance.svg") }
    ];

    Rectangle {
        border_radius: MaterialStyleMetrics.border_radius_28;
        background: MaterialPalette.surface_bright;
        height: 100%;

        HorizontalLayout {
            spacing: 4px;
            padding: 3px;
            height: 100%;

            for profile in root.profiles: top_rect := Rectangle {
                width: self.height + 10px;
                border_radius: MaterialStyleMetrics.border_radius_28;

                elevation := Elevation {
                    border_radius: parent.border_radius;
                    background: MaterialPalette.primary; 
                    width: 100%;
                    height: 100%;
                }

                base := BaseButton {
                    border_radius: parent.border_radius;
                    icon: profile.icon;
                    icon-size: 20px;
                    button_horizontal_padding: 0px;
                    icon_color: root.powerProfile == profile.name ? MaterialPalette.on_primary : transparent;

                    clicked => {
                        root.set_power_profile(profile.name);
                    }
                }

                states [
                    disabled when !(root.powerProfile == profile.name): {
                        elevation.background: transparent;
                        base.color: MaterialPalette.on_surface;
                    }
                    hover when base.has-hover && !base.pressed && !base.enter_pressed: {
                        elevation.level: 2;
                    }
                ]
            }
        }
    }
}
