import {
    Elevation,
    ScrollView,
    MaterialPalette,
    MaterialTypography,
    MaterialStyleMetrics,
} from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";
import { MaterialText, MaterialPalette } from "../material-1.0/material.slint";
import { TaskbarConfigSlint } from "../shared-items.slint";

export struct Window {
    id: int,
    app_id: string,
    title: string,
    icon: image,
    is_focused: bool,
    is_hovered_slint: bool,
}

export struct Workspace {
    id: int,
    windows: [Window],
}

export component Taskbar inherits Rectangle {
    in-out property <[Workspace]> workspaces;
    in property <TaskbarConfigSlint> config;
    in property <float> animation_multiplier;

    callback dispatch_command(string);

    ScrollView {
        overlay_scrollbars: true;
        horizontal_scroll: true;

        HorizontalLayout {
            alignment: center;
            height: 100%;
            spacing: 16px;
            padding-left: 8px;
            padding-right: 8px;

            for ws[i] in root.workspaces: Rectangle {
                border_radius: MaterialStyleMetrics.border_radius_28;
                background: MaterialPalette.surface_bright;
                height: 100%;
                width: layout.preferred-width;

                layout := HorizontalLayout {
                    height: 100%;
                    spacing: 4px;
                    padding: 4px;

                    for win[j] in ws.windows: Rectangle {
                        height: 100%;
                        width: base.preferred-width;

                        callback clicked <=> base.clicked;

                        accessible-role: button;
                        accessible-enabled: win.is_focused;
                        accessible-action-default => {
                            base.clicked();
                        }

                        elevation := Elevation {
                            border_radius: root.height / 2;
                            background: MaterialPalette.primary;
                            width: 100%;
                            height: 100%;
                        }

                        base := BaseButton {
                            icon: win.icon;
                            icon-size: config.icon-size;
                            text_length: config.max-text-lenght;
                            animation_multiplier: animation_multiplier;

                            text: win.is_hovered_slint ? win.title : "";

                            padding-right: 1rem;
                            icon_color: transparent;
                            border_radius: elevation.border_radius;
                            color: MaterialPalette.on_primary;
                            height: 100%;
                            button_horizontal_padding: MaterialStyleMetrics.padding_8;

                            property <bool> hover_sentinel: self.has-hover;
                            changed hover_sentinel => {
                                win.is_hovered_slint = hover_sentinel;
                            }

                            pointer-event(event) => {
                                if (event.kind == PointerEventKind.up) {

                                    if (event.button == PointerEventButton.left) {
                                        dispatch_command("niri msg action focus-window --id \{win.id}");
                                    }
                                    if (event.button == PointerEventButton.middle) {
                                        dispatch_command("niri msg action close-window --id \{win.id}");
                                    }
                                }
                            }
                        }

                        states [
                            disabled when !win.is_focused: {
                                elevation.background: transparent;
                                base.color: MaterialPalette.on_surface;
                            }
                            hover when win.is_hovered_slint && !base.pressed && !base.enter_pressed: {
                                elevation.level: 2;
                            }
                        ]
                    }
                }
            }
        }
    }
}
