import {
    Elevation,
    ScrollView,
    MaterialPalette,
    MaterialTypography,
    MaterialStyleMetrics,
} from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";
import { MaterialText, MaterialPalette } from "../material-1.0/material.slint";

export struct Window {
    id: int,
    app_id: string,
    title: string,
    icon: image,
    is_focused: bool,
}

export struct Workspace {
    id: int,
    windows: [Window],
}

export component Taskbar inherits Rectangle {
    in property <[Workspace]> workspaces;
    in property <length> icon-size;
    in property <length> max-text-lenght;
    callback dispatch_command(string);
        width: 60%;

    ScrollView {
        overlay_scrollbars: true;
        horizontal_scroll: true;

        HorizontalLayout {
            alignment: center;
            height: 100%;
            spacing: 16px;
            padding-left: 8px;
            padding-right: 8px;

            for ws[i] in root.workspaces: Rectangle {
                border_radius: MaterialStyleMetrics.border_radius_28;
                background: MaterialPalette.surface_bright;
                height: 100%;

                width: layout.preferred-width;

                layout := HorizontalLayout {
                    height: 100%;
                    spacing: 4px;
                    padding: 4px;

                    for win[j] in ws.windows: Rectangle {
                        height: 100%;
                        width: base.preferred-width;

                        callback clicked <=> base.clicked;

                        accessible-role: button;
                        accessible-enabled: win.is_focused;
                        accessible-action-default => {
                            base.clicked();
                        }

                        elevation := Elevation {
                            border_radius: root.height / 2;
                            background: MaterialPalette.primary;
                            width: 100%;
                            height: 100%;
                        }

                        base := BaseButton {
                            icon: win.icon;
                            icon-size: root.icon-size;
                            text_length: root.max-text-lenght;
                            text: (self.has-hover || self.pressed) || self.pressed ? win.title : "";
                            icon_color: transparent;
                            border_radius: elevation.border_radius;
                            color: MaterialPalette.on_primary;
                            height: 100%;
                            button_horizontal_padding: MaterialStyleMetrics.padding_8;
                            pointer-event(event) => {
                                if (event.button == PointerEventButton.left) {
                                    dispatch_command("niri msg action focus-window --id \{win.id}" );
                                }
                                if (event.button == PointerEventButton.middle) {
                                    dispatch_command("niri msg action close-window --id \{win.id}");
                                }
                                if (event.button == PointerEventButton.right) {
                                }
                            }
                        }

                        states [
                            disabled when !win.is_focused: {
                                elevation.background: transparent;
                                base.color: MaterialPalette.on_surface;
                            }
                            hover when base.has_hover && !base.pressed && !base.enter_pressed: {
                                elevation.level: 2;
                            }
                        ]
                    }
                }
            }
        }
    }
}
