import {
    Elevation,
    ScrollView,
    MaterialPalette,
    MaterialTypography,
    MaterialStyleMetrics,
    CheckBox,
    RadioButton,
    CheckState,
    VerticalDivider,
} from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";
import { TrayConfigSlint } from "../shared-items.slint";

export struct TrayItemSlint { id: string, title: string, icon: image, status: string, active: bool }
export struct ContextMenuActionSlint {
    id: string,
    label: string,
    icon: image,
    has_icon: bool,
    is_destructive: bool,
    is_separator: bool,
    toggle_state: int,
    depth: int
}
export struct ContextMenuDataSlint {
    visible: bool,
    item_id: string,
    title: string,
    x_pos: length,
    actions: [ContextMenuActionSlint]
}

export component TrayItem inherits Rectangle {
    in property <TrayItemSlint> item;
    in property <length> icon-size;
    background: item.active ? MaterialPalette.secondary : MaterialPalette.surface_variant;
    border_radius: MaterialStyleMetrics.border_radius_8;
    padding: MaterialStyleMetrics.padding_8;

    Image {
        source: root.item.icon;
        width: root.icon-size;
        height: root.icon-size;
    }
}

export component TrayRow inherits Rectangle {
    in property <[TrayItemSlint]> items;
    in property <TrayConfigSlint> config;
    height: 100%;

    callback item_clicked(string, string, length);
    Rectangle {
        border_radius: MaterialStyleMetrics.border_radius_28;
        background: MaterialPalette.surface_bright;
        height: 100%;

        HorizontalLayout {
            spacing: 4px;
            padding: 3px;
            height: 100%;

            for tray-item in root.items: top_rect := Rectangle {
                width: self.height + 10px;
                border_radius: MaterialStyleMetrics.border_radius_28;

                elevation := Elevation {
                    border_radius: parent.border_radius;
                    width: 100%;
                    height: 100%;
                }

                base := BaseButton {
                    border_radius: parent.border_radius;
                    icon: tray-item.icon;
                    icon-size: config.icon-size;
                    button_horizontal_padding: 0px;
                    icon_color: transparent;

                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.up) {
                            if (event.button == PointerEventButton.left) {
                                root.item_clicked(tray-item.id, "left", 0);
                            } else if (event.button == PointerEventButton.right) {
                                root.item_clicked(
                                tray-item.id, 
                                "right", 
                                root.x + top_rect.x + top_rect.width / 2);
                            }
                        }
                    }
                }

                states [
                    disabled when !tray-item.active: {
                        elevation.background: transparent;
                        base.color: MaterialPalette.on_surface;
                    }
                    hover when base.has_hover && !base.pressed && !base.enter_pressed: {
                        elevation.level: 2;
                    }
                ]
            }
        }
    }
}

export component TrayContextMenu inherits Rectangle {
    in property <ContextMenuDataSlint> menuData;
    in property <TrayConfigSlint> config;
    in property <float> animation_multiplier;

    callback menu_action_executed(string, string);
    animate x {
        duration: 300ms * animation_multiplier;
        easing: ease-in-out-back;
    }
    clip: true;
    animate height {
        duration: 350ms * animation_multiplier;
        easing: ease-in-out-back;
    }
    width: config.width;
    height: root.menuData.visible ? Math.min(layout.preferred-height + 30px, config.max-height) : 0px;
    TouchArea {

        elevation := Elevation {
            level: 2;
            border_radius: MaterialStyleMetrics.border_radius_16;
            background: MaterialPalette.surface_container_low;
            width: 100%;
            height: 100%;
            HorizontalLayout {
                padding: 5px;
                padding-top: 15px;
                alignment: center;
                ScrollView {
                    has-focus: true;
                    width: 100%;
                    height: 100%;
                    layout := VerticalLayout {
                        padding: MaterialStyleMetrics.padding_8;

                        if root.menuData.title != "": Text {
                            text: root.menuData.title;
                            font-size: MaterialTypography.body_small.font_size;
                            color: MaterialPalette.on_surface_variant;
                            horizontal-alignment: center;
                            height: 25px;
                        }

                        if root.menuData.title != "": Rectangle {
                            height: 1px;
                            background: MaterialPalette.outline_variant;
                        }

                        VerticalLayout {
                            spacing: 4px;
                            padding-top: 4px;

                            for action in root.menuData.actions: VerticalLayout {
                                if action.is_separator: Rectangle {
                                    height: 9px;
                                    VerticalDivider {
                                        width: 100%;
                                        height: 1px;
                                    }
                                }

                                if !action.is_separator: Rectangle {
                                    height: 28px;
                                    border_radius: MaterialStyleMetrics.border_radius_28;

                                    item_elevation := Elevation {
                                        border_radius: parent.border_radius;
                                        background: transparent;
                                        width: 100%;
                                        height: 100%;
                                    }

                                    Rectangle {
                                        width: 100%;
                                        height: 100%;

                                        if action.depth > 0: Rectangle {
                                            x: 4px + (action.depth * 8px);
                                            width: 1.5px;
                                            height: 75%;
                                            background: MaterialPalette.outline.with_alpha(40%);
                                        }

                                        HorizontalLayout {
                                            padding-left: 8px + (action.depth * 14px);
                                            spacing: 8px;
                                            alignment: start;

                                            if action.toggle_state != 0: Rectangle {
                                                width: 24px;
                                                height: 100%;

                                                if action.toggle_state == 2 || action.toggle_state == 3: CheckBox {
                                                    check_state: action.toggle_state == 2 ? CheckState.checked : CheckState.unchecked;
                                                    enabled: true;
                                                }
                                                if action.toggle_state == 4: RadioButton {
                                                    checked: true;
                                                    enabled: true;
                                                }
                                            }

                                            if action.has_icon: VerticalLayout {
                                                alignment: center;
                                                Image {
                                                    source: action.icon;
                                                    width: config.menu-icon-size;
                                                    height: config.menu-icon-size;
                                                }
                                            }

                                            Text {
                                                text: action.label;
                                                color: action.is_destructive ? MaterialPalette.error : MaterialPalette.on_surface;
                                                font-size: MaterialTypography.label_medium.font-size;
                                                font-weight: action.depth > 0 ? MaterialTypography.label_small.font_weight : MaterialTypography.label_medium.font_weight;
                                                vertical-alignment: center;
                                                overflow: elide;
                                            }
                                        }
                                    }

                                    base_item := BaseButton {
                                        width: 100%;
                                        height: 100%;
                                        border_radius: parent.border_radius;
                                        color: transparent;
                                        clicked => {
                                            root.menu_action_executed(root.menuData.item_id, action.id);
                                        }
                                    }

                                    states [
                                        hover when base_item.has_hover: {
                                            item_elevation.background: MaterialPalette.surface_container_highest;
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
