[package]
name = "koia-shell"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
config = "0.15.25"
dirs = "6.0.0"
env_logger = "0.11.11"
freedesktop-desktop-entry = "0.8.1"
freedesktop-icons = "0.4.0"
futures = "0.3.32"
image = { version = "0.25.10", default-features = false, features = ["png"] }
log = "0.4.33"
niri-ipc = "26.4.0"
serde = "1.0.228"
slint = { version = "=1.17.1", default-features = false, features = [
    "renderer-skia",
    "std",
    "backend-winit",
] }
spell-framework = { git = "https://github.com/themkoi/Spell", rev = "d12e7f21fd2c60ef81e730c111d4706dd4963cbe" }
toml = "1.1.2"
tokio = "1.52.3"
notify = "8.2.0"

chrono = "0.4.45"
serde_json = "1.0.150"
upower_dbus = { git = "https://github.com/pop-os/dbus-settings-bindings", rev = "eed01dd3609e90e3c8cd043656734c500956c793" , package = "upower_dbus" }
zbus = "5.16.0"
wayle-audio = "0.1.4"
system-tray = "0.8.7"
wayle-power-profiles = "0.1.4"
wayle-network = "0.1.2"
wayle-bluetooth = "0.1.2"
ddc-hi = "0.4.1"

[features]
default = ["framework"]
framework = []
default_hardware = []

[build-dependencies]
slint-build = "=1.17.1"

[profile.dev]
debug = 2
split-debuginfo = "unpacked"
incremental = true
codegen-units = 256
opt-level = 0
lto = false
panic = "abort"

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
debug = 0
debug-assertions = false
