import {
    MaterialPalette,
    MaterialTypography,
    MaterialStyleMetrics,
    MaterialText,
    ScrollView,
    StateLayer,
    IconButton,
} from "@material/material.slint";

export component SelectionButton {
    in property <string> text <=> text-label.text;
    in property <image> icon <=> icon-image.source;
    in property <bool> enabled: true;
    in-out property <bool> checked;

    callback clicked();

    min-width: content-layer.min-width;
    accessible-label: root.text;
    accessible-role: button;
    accessible-checkable: true;
    accessible-checked: root.checked;
    accessible-action-default => { touch-area.clicked(); }
    forward-focus: focus_scope;

    touch-area := TouchArea {
        width: 100%;
        height: 100%;
        enabled: root.enabled;

        clicked => {
            root.clicked();
        }
    }

    focus_scope := FocusScope {
        width: 0px;
        height: 0px;
        enabled: root.enabled;

        key_pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                touch-area.clicked();
                return accept;
            }
            return reject;
        }
    }

    state-layer := StateLayer {
        enabled: root.enabled;
        pressed: touch-area.pressed;
        has-hover: touch-area.has-hover;
        has-focus: focus_scope.has-focus;
        background: text-label.color;
    }

    content-layer := HorizontalLayout {
        alignment: center;
        padding-left: 8px;
        padding-right: 8px;
        spacing: 8px;

        text-label := MaterialText {
            vertical-alignment: center;
            color: MaterialPalette.on_surface_variant;
            style: MaterialTypography.label_large;
        }

        icon-image := Image {
            y: (parent.height - self.height) / 2;
            width: MaterialStyleMetrics.size_18;
            colorize: MaterialPalette.on_surface_variant;
            transform-rotation: root.checked ? 180deg : 0deg;

            animate transform-rotation { duration: 250ms; }
        }
    }

    states [
        disabled when !root.enabled: {
            root.opacity: 0.38;
        }
    ]
}