pub(crate) mod taskbar;
pub(crate) mod volume;
pub(crate) mod brightness;
pub(crate) mod tray;
pub(crate) mod battery;
pub(crate) mod power_profiles;
pub(crate) mod time;
pub(crate) mod notifications;
pub(crate) mod hardware_specific;
