// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { MaterialPalette } from "../styling/material_palette.slint";

export component ScrollBar {
    in property <bool> enabled;
    out property <bool> has_hover: touch_area.has_hover;
    in_out property <bool> horizontal;
    in_out property <length> maximum;
    in_out property <length> page_size;
    in_out property <length> value;
    in property <ScrollBarPolicy> policy: ScrollBarPolicy.as_needed;

    property <length> track_size: root.horizontal ? root.width - 2 * root.offset : root.height - 2 * offset;
    property <length> step_size: 10px;
    property <length> offset: 2px;
    property <float> state_opacity: 40%;

    visible: (self.policy == ScrollBarPolicy.always_on) || (self.policy == ScrollBarPolicy.as_needed && self.maximum > 0);

    Rectangle {
        clip: true;

        thumb := Rectangle {
            width: !root.horizontal ? parent.width : root.maximum <= 0phx ? 0phx : max(min(32px, root.width), root.track-size * root.page-size / (root.maximum + root.page-size));
            height: root.horizontal ? parent.height : root.maximum <= 0phx ? 0phx : max(min(32px, root.height), root.track-size * (root.page-size / (root.maximum + root.page-size)));
            x: !root.horizontal ? (parent.width - self.width) / 2 : root.offset + (root.track-size - thumb.width) * (-root.value / root.maximum);
            y: root.horizontal ? (parent.height - self.height) / 2 : root.offset + (root.track-size - thumb.height) * (-root.value / root.maximum);
            border-radius: (root.horizontal ? self.height : self.width) / 2;
            background: MaterialPalette.on_background;
            opacity: hide_timer.running || touch_area.has_hover || touch_area.pressed ? root.state_opacity : 0;

            animate opacity { duration: 150ms; }
        }
    }

    touch_area := TouchArea {
        property <length> pressed_value;

        width: parent.width;
        height: parent.height;

        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                self.pressed-value = -root.value;
            }
        }

        moved => {
            if (self.enabled && self.pressed) {
                root.value = -max(0px, min(root.maximum, self.pressed-value + (root.horizontal ? (touch-area.mouse-x - touch-area.pressed-x) * (root.maximum / (root.track-size - thumb.width)) : (touch-area.mouse-y - touch-area.pressed-y) * (root.maximum / (root.track-size - thumb.height)))));
            }
        }

        scroll-event(event) => {
            if (root.horizontal && event.delta-x != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta-x));
                return accept;
            } else if (!root.horizontal && event.delta-y != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta-y));
                return accept;
            }
            reject
        }

        changed has_hover => {
            if !self.has_hover && !hide_timer.running {
                hide_timer.running = true;
            }
        }

        changed pressed => {
            if self.pressed && hide_timer.running {
                hide_timer.running = false;
            }
        }
    }

    changed value => {
        if !self.has_hover && !hide_timer.running {
            hide_timer.running = true;
        }
    }

    hide_timer := Timer {
        interval: 1.5s;
        running: false;

        triggered => {
            self.running = false;
        }
    }

    states [
        pressed when touch_area.pressed: {
            root.state_opacity: 80%;
        }
        hover when root.has_hover: {
            root.state_opacity: 70%;
        }
    ]
}

export component ScrollView {
    in property <bool> enabled: true;
    out property <length> visible_width <=> flickable.width;
    out property <length> visible_height <=> flickable.height;
    in_out property <length> viewport_width <=> flickable.viewport_width;
    in_out property <length> viewport_height <=> flickable.viewport_height;
    in_out property <length> viewport_x <=> flickable.viewport_x;
    in_out property <length> viewport_y <=> flickable.viewport_y;
    in property <ScrollBarPolicy> vertical_scrollbar_policy <=> vertical_bar.policy;
    in property <ScrollBarPolicy> horizontal_scrollbar_policy <=> horizontal_bar.policy;

    in property <bool> overlay_scrollbars: false;
    in property <bool> horizontal_scroll: false;

    in property <bool> hide_scrollbars: false;

    in_out property <bool> has_focus;
    callback scrolled <=> flickable.flicked;

    property <length> scroll_bar_size: 8px;
    property <length> scroll_bar_padding: 1px;

    property <length> scroll_x_target: 0px;
    property <length> scroll_y_target: 0px;

    min_height: 50px;
    min_width: 50px;
    horizontal_stretch: 1;
    vertical_stretch: 1;
    preferred_height: 100%;
    preferred_width: 100%;

    flickable := Flickable {
        x: 0;
        y: 0;

        viewport_x <=> root.scroll_x_target;
        viewport_y <=> root.scroll_y_target;

        animate viewport_x {
            duration: 120ms;
            easing: ease-out;
        }
        animate viewport_y {
            duration: 120ms;
            easing: ease-out;
        }

        width: root.width - (!root.overlay_scrollbars && root.vertical_scrollbar_policy != ScrollBarPolicy.always_off && !root.horizontal_scroll ? root.scroll_bar_size - 2 * root.scroll_bar_padding : 0);
        height: root.height - (!root.overlay_scrollbars && (root.horizontal_scrollbar_policy != ScrollBarPolicy.always_off || root.horizontal_scroll) ? root.scroll_bar_size : 0);

        TouchArea {
            width: parent.viewport_width;
            height: parent.viewport_height;

            scroll-event(event) => {
                let speed_multiplier = 2.0;
                let adjusted_delta = event.delta-y * speed_multiplier;

                if (root.horizontal_scroll) {
                    let max_scroll = Math.min(0px, -(flickable.viewport_width - flickable.width));
                    root.scroll_x_target = Math.max(max_scroll, Math.min(0px, root.scroll_x_target - adjusted_delta));
                    root.scroll_y_target = 0px;
                } else {
                    let max_scroll = Math.min(0px, -(flickable.viewport_height - flickable.height));
                    root.scroll_y_target = Math.max(max_scroll, Math.min(0px, root.scroll_y_target - adjusted_delta));
                    root.scroll_x_target = 0px;
                }
                return accept;
            }
        }

        @children
    }

    left_shadow := Rectangle {
        x: 0;
        y: 0;
        width: 15px;
        height: flickable.height + horizontal_bar.height;
        opacity: flickable.viewport_x < 0px ? 1.0 : 0.0;
        animate opacity { duration: 200ms; }
        clip: true; 

        Rectangle {
            x: -5px;
            y: 25px;
            width: 5px;
            height: parent.height - 50px; 
            background: rgba(0, 0, 0, 0.60);
            drop-shadow-blur: 12px;
            drop-shadow-color: rgba(0, 0, 0, 0.90);
        }
    }

    right_shadow := Rectangle {
        x: flickable.width - self.width;
        y: 0;
        width: 15px;
        height: flickable.height + horizontal_bar.height;
        opacity: (flickable.viewport_width + flickable.viewport_x) > flickable.width ? 1.0 : 0.0;
        animate opacity { duration: 200ms; }
        clip: true;

        Rectangle {
            x: parent.width;
            y: 25px;
            width: 5px;
            height: parent.height - 50px;
            background: rgba(0, 0, 0, 0.60);
            drop-shadow-blur: 12px;
            drop-shadow-color: rgba(0, 0, 0, 0.90);
        }
    }

    top_shadow := Rectangle {
        x: 0;
        y: 0;
        width: flickable.width + vertical_bar.width;
        height: 15px;
        opacity: root.horizontal_scroll ? 0.0 : (flickable.viewport_y < 0px ? 1.0 : 0.0);
        animate opacity { duration: 200ms; }
        clip: true;

        Rectangle {
            x: 25px;
            y: -5px; 
            width: parent.width - 50px; 
            height: 5px;
            background: rgba(0, 0, 0, 0.60);
            drop-shadow-blur: 12px;
            drop-shadow-color: rgba(0, 0, 0, 0.90);
        }
    }

    bottom_shadow := Rectangle {
        x: 0;
        y: flickable.height - self.height;
        width: flickable.width + vertical_bar.width;
        height: 15px;
        opacity: root.horizontal_scroll ? 0.0 : ((flickable.viewport_height + flickable.viewport_y) > flickable.height ? 1.0 : 0.0);
        animate opacity { duration: 200ms; }
        clip: true;

        Rectangle {
            x: 25px;
            y: parent.height;
            width: parent.width - 50px;
            height: 5px;
            background: rgba(0, 0, 0, 0.60);
            drop-shadow-blur: 12px;
            drop-shadow-color: rgba(0, 0, 0, 0.90);
        }
    }
    vertical_bar := ScrollBar {
        enabled: root.enabled && !root.horizontal_scroll;
        visible: !hide_scrollbars;
        x: root.overlay_scrollbars ? parent.width - self.width - root.scroll_bar_padding : flickable.width + root.scroll_bar_padding;
        y: 0;
        width: root.vertical_scrollbar_policy != ScrollBarPolicy.always_off && !root.horizontal_scroll ? root.scroll_bar_size : 0;
        height: root.vertical_scrollbar_policy != ScrollBarPolicy.always_off ? (root.overlay_scrollbars ? parent.height : parent.height - horizontal_bar.height) : parent.height;
        horizontal: false;

        value <=> root.scroll_y_target;
        maximum: root.horizontal_scroll ? 0px : (flickable.viewport_height - flickable.height);
        page-size: flickable.height;

        animate value {
            duration: 120ms;
            easing: ease-out;
        }
    }

    horizontal_bar := ScrollBar {
        enabled: root.enabled;
        visible: !hide_scrollbars;
        width: root.overlay_scrollbars ? parent.width : (vertical_bar.visible ? parent.width - vertical_bar.width : parent.width);
        height: root.horizontal_scrollbar_policy != ScrollBarPolicy.always_off || root.horizontal_scroll ? root.scroll_bar_size : 0;
        x: 0;
        y: root.overlay_scrollbars ? parent.height - self.height : flickable.height + root.scroll_bar_padding;
        horizontal: true;

        value <=> root.scroll_x_target;
        maximum: flickable.viewport_width - flickable.width;
        page_size: flickable.width;

        animate value {
            duration: 120ms;
            easing: ease-out;
        }
    }
}
