// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component SliderBase {
    in property <bool> enabled <=> touch-area.enabled;
    in property <float> minimum: 0;
    in property <float> maximum: 100;
    in property <float> step: 1;
    in property <Orientation> orientation;
    in property <length> handle-x;
    in property <length> handle-y;
    in property <length> handle-width;
    in property <length> handle-height;
    out property <bool> pressed <=> touch-area.enabled;
    out property <bool> has-hover <=> touch-area.has-hover;
    out property <bool> vertical: root.orientation == Orientation.vertical;
    out property <bool> has-focus <=> focus-scope.has-focus;
    out property <bool> handle-has-hover: touch-area.mouse-x >= root.handle-x && touch-area.mouse-x <= root.handle-x + root.handle-width &&
        touch-area.mouse-y >= root.handle-y && touch-area.mouse-y <= root.handle-y + root.handle-height;
    out property <bool> handle-pressed;
    in-out property <int> value: minimum;

    callback changed(value: float);
    callback released(value: float);

    private property <length> ref-size: !root.vertical ? root.handle-width : root.handle-height;

    forward-focus: focus-scope;

    touch-area := TouchArea {
        property <float> pressed-value;

        width: 100%;
        height: 100%;

        pointer-event(event) => {
            if (event.button != PointerEventButton.left) {
                return;
            }
            if (event.kind == PointerEventKind.up) {
                if (root.handle-pressed) {
                    root.released(root.value);
                }
                root.handle-pressed = false;
                return;
            }
            if (!root.handle-has-hover) {
                root.set-value((!root.vertical ? root.size-to-value(touch-area.mouse-x, root.width) :
                    root.size-to-value(root.height - touch-area.mouse-y, root.height)) + root.minimum);
            }
            self.pressed-value = value;
            focus-scope.focus();
            root.handle-pressed = true;
        }

        moved => {
            if (!self.enabled) {
                return;
            }
            root.set-value(self.pressed-value + (!vertical ? root.size-to-value(touch-area.mouse-x - touch-area.pressed-x, root.width - root.ref-size) :
                root.size-to-value(touch-area.pressed-y - touch-area.mouse-y, root.height - root.ref-size)));
        }
    }

    focus-scope := FocusScope {
        x: 0;
        y: 0;
        width: 0;
        height: 0;
        enabled: root.enabled;

        key-pressed(event) => {
            if (!self.enabled || root.step <= 0) {
                return reject;
            }
            if ((!vertical && event.text == Key.RightArrow) || (vertical && event.text == Key.UpArrow)) {
                root.increment();
                return accept;
            } else if ((!vertical && event.text == Key.LeftArrow) || (vertical && event.text == Key.DownArrow)) {
                root.decrement();
                return accept;
            } else if (event.text == Key.Home) {
                root.set-value(root.minimum);
                return accept;
            } else if (event.text == Key.End) {
                root.set-value(root.maximum);
                return accept;
            }
            reject
        }

        key-released(event) => {
            if (!self.enabled) {
                return reject;
            }
            if (!vertical && event.text == Key.RightArrow) || (vertical && event.text == Key.DownArrow)
                || (!vertical && event.text == Key.LeftArrow) || (vertical && event.text == Key.UpArrow)
                || event.text == Key.Home || event.text == Key.End {
                root.released(root.value);
            }
            return accept;
        }
    }

    pure function size-to-value(size: length, range: length) -> float {
        size * (root.maximum - root.minimum) / range;
    }

    public function set-value(value: float) {
        if (root.value == value) {
            return;
        }
        root.value = max(root.minimum, min(root.maximum, value));
        root.changed(root.value);
    }

    public function increment() {
        root.set-value(root.value + root.step);
    }

    public function decrement() {
        root.set-value(root.value - root.step);
    }
}

// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT
//
import { MaterialStyleMetrics } from "../styling/material_style_metrics.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { StateLayer } from "./state_layer.slint";

export component Slider {
    in property <Orientation> orientation <=> base.orientation;
    in property <float> maximum <=> base.maximum;
    in property <float> minimum <=> base.minimum;
    in property <float> step <=> base.step;
    in property <bool> enabled <=> base.enabled;
    out property <bool> has-focus <=> base.has-focus;
    in-out property <int> value <=> base.value;
    in property <int> stop-count: 0;
    in property <color> background_color: MaterialPalette.surface_container_highest;
    in property <color> active_color: MaterialPalette.primary;

    in property <length> length: 200px;
    in property <length> thickness: MaterialStyleMetrics.size_16;
    in property <length> thumb-width: base.vertical ? root.thickness * 3.5 : root.thickness * 0.6;
    in property <length> thumb-height: base.vertical ? root.thickness * 0.6 : root.thickness * 3.5;
    
    in property <length> thumb-padding: 0px;
    in property <length> track-gap: 4px;

    callback changed <=> base.changed;
    
    callback released(int);

    min-width: base.vertical ? root.thickness : 100px;
    min-height: base.vertical ? 100px : root.thickness;
    preferred-width: base.vertical ? root.thickness : root.length;
    preferred-height: base.vertical ? root.length : root.thickness;
    
    vertical-stretch: base.vertical ? 1 : 0;
    horizontal-stretch: base.vertical ? 0 : 1;

    accessible-role: slider;
    accessible-enabled: root.enabled;
    accessible-orientation: root.orientation;
    accessible-value: root.value;
    accessible-value-minimum: root.minimum;
    accessible-value-maximum: root.maximum;
    accessible-value-step: min(root.step, (root.maximum - root.minimum) / 100);

    accessible-action-set-value(v) => {
        if v.is-float() {
            base.set-value(v.to-float());
        }
    }
    accessible-action-increment => { base.increment(); }
    accessible-action-decrement => { base.decrement(); }
    forward-focus: base;

    track := Rectangle {
        x: base.vertical ? (parent.width - self.width) / 2 : 0;
        y: base.vertical ? 0 : (parent.height - self.height) / 2;
        
        width: base.vertical ? root.thickness : parent.width; 
        height: base.vertical ? parent.height : root.thickness;
        background: root.background_color;
        border_radius: (base.vertical ? self.width : self.height) / 2;

        // Active Track Filler
        Rectangle {
            x: 0;
            y: base.vertical ? thumb.y + thumb.height - root.thumb-padding + root.track-gap : 0;
            
            width: base.vertical ? parent.width : max(thumb.x + root.thumb-padding - root.track-gap, 0px);
            height: base.vertical ? max(parent.height - (thumb.y + thumb.height - root.thumb-padding + root.track-gap), 0px) : parent.height;
            
            border-top-left-radius: base.vertical ? MaterialStyleMetrics.size_1 : track.border_radius;
            border-bottom-left-radius: track.border_radius;
            border-top-right-radius: base.vertical ? MaterialStyleMetrics.size_1 : MaterialStyleMetrics.size_1;
            border-bottom-right-radius: base.vertical ? track.border_radius : MaterialStyleMetrics.size_1;
            background: root.active_color;
        }

        if root.stop-count > 1: Rectangle {
            width: 100%;
            height: 100%;

            property <float> steps: (root.maximum - root.minimum) / (root.stop-count * 1.0);

            for i in root.stop-count - 1: Rectangle {
                x: !base.vertical ? (track.width * ((root.minimum + (i + 1) * steps) - root.minimum) / (root.maximum - root.minimum) - self.width / 2) : (parent.width - self.width) / 2;
                y: base.vertical ? (track.height * (root.maximum - (root.minimum + (i + 1) * steps)) / (root.maximum - root.minimum) - self.height / 2) : (parent.height - self.height) / 2;
                height: MaterialStyleMetrics.size_4;
                width: self.height;
                border_radius: self.height / 2;
                background: MaterialPalette.outline;
            }
        }
    }

    thumb := Rectangle {
        x: base.vertical ? (parent.width - self.width) / 2 : clamp((parent.width - self.width) * (root.value - root.minimum) / (root.maximum - root.minimum), 0, parent.width - self.width);
        y: base.vertical ? clamp((parent.height - self.height) * (root.maximum - root.value) / (root.maximum - root.minimum), 0, parent.height - self.height) : (parent.height - self.height) / 2;
        
        width: root.thumb-width;
        height: root.thumb-height;
        background: transparent;

        ripple-container := Rectangle {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            width: visual-thumb.width + MaterialStyleMetrics.size_14;
            height: visual-thumb.height + MaterialStyleMetrics.size_14;

            StateLayer {
                x: 0;
                y: 0;
                width: parent.width;
                height: parent.height;
                border_radius: min(parent.width, parent.height) / 2;

                pressed: base.handle-pressed;
                has_hover: base.handle-has-hover;
                has_focus: base.has-focus;
                enabled: root.enabled;

                background: root.active_color;
                display_background: base.handle-pressed
                    || base.handle-has-hover
                    || base.has-focus;
            }
        }

        visual-thumb := Rectangle {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            width: max(0px, parent.width - root.thumb-padding * 2);
            height: max(0px, parent.height - root.thumb-padding * 2);
            border_radius: min(self.width, self.height) / 2;
            background: root.active_color;
        }
    }

    base := SliderBase {
        width: 100%;
        height: 100%;
        handle-x: thumb.x;
        handle-y: thumb.y;
        handle-width: thumb.width;
        handle-height: thumb.height;

        released(val) => {
            self.clear-focus();
            root.released(val);
        }
    }
}