// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { MaterialText } from "./material_text.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialTypography } from "../styling/material_typography.slint";

export component ToolTipMaterial {
    in property <string> text;


    background_layer := Rectangle {
        border_radius: 4px;
        background: MaterialPalette.surface;

        layout := HorizontalLayout {
            max_width: 200px;
            padding_top: 4px;
            padding_bottom: 4px;
            padding_left: 8px;
            padding_right: 8px;

            MaterialText {
                text: root.text;
                vertical_alignment: center;
                color: MaterialPalette.inverse_surface;
                style: MaterialTypography.body_medium;
                wrap: word-wrap;
            }
        }
    }
}