import { Palette } from "std-widgets.slint";

import { FilledButton } from "@material/material.slint";
import { MaterialPalette } from "@material/material.slint";
import { MaterialScheme } from "@material/material.slint";
import { MaterialSchemes } from "@material/material.slint";
import {
    MaterialTypography,
    MaterialStyleMetrics,
} from "@material/material.slint";

export struct TaskbarConfigSlint {
    icon_size: length,
    max-text-lenght: length,
}


export struct ConfigSlint {
    taskbar: TaskbarConfigSlint,
}

export { MaterialPalette }
export { MaterialScheme }
export { MaterialSchemes }
export {Palette}

import { Workspace, Taskbar } from "components/taskbar.slint";


export component barWindow inherits Window {
    in property <[Workspace]> workspaces;
    in property <ConfigSlint> config;
    padding: 0px;
    in-out property <int> counter: 42;
    default-font-size: 10px;
    background: MaterialPalette.surface_container;

    callback request-increase-value();
    callback run_command(string);

    Rectangle {
        width: 100%;
        height: 100%;

        HorizontalLayout {
            width: 100%;
            height: 100%;
            padding: 0px;
            spacing: 0px;

            FilledButton {
                text: "text button";
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            Taskbar {
                width: 60%;
                height: 70%;
                icon-size: config.taskbar.icon-size;
                max-text-lenght: config.taskbar.max-text-lenght;
                workspaces: workspaces;
                dispatch_command(cmd) => {
                    root.run_command(cmd);
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            FilledButton {
                text: "Test button";
            }
        }
    }
}
