import { Palette } from "std-widgets.slint";
import { FilledButton, Elevation } from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";
import { MaterialPalette } from "@material/material.slint";
import { TaskbarConfigSlint, ConfigSlint } from "shared-items.slint";

import { Workspace, Taskbar } from "components/taskbar.slint";
import {TrayRow, TrayContextMenu, TrayItemSlint, ContextMenuDataSlint } from "components/tray.slint";

export struct VolumeDataSlint { volume: int, muted: bool}
export struct BatteryDataSlint { percentage: int, state: string}

export component barWindow inherits Window {
    in property <[Workspace]> workspaces;
    in property <[TrayItemSlint]> tray;
    in property <ContextMenuDataSlint> trayMenu;
    in property <int> brightness;
    in property <BatteryDataSlint> batteryData;
    in property <VolumeDataSlint> volumeData;

    in property <ConfigSlint> config;
    in-out property <length> window_width <=> self.width;

    default-font-size: 10px;
    background: transparent;

    callback run_command(string);
    callback set_volume(int, int);
    callback set_muted(bool);
    callback set_brightness(int, int);
    callback tray_item_clicked(string, string, length);
    callback menu_action_executed(string, string);
    callback manage_touch(string ,bool, length, length, length, length);

    Rectangle {
        cache-rendering-hint: true;
        width: 100%;
        height: 100%;

        main_bar := Rectangle {
            x: 0px;
            y: 0px;
            background: MaterialPalette.surface_container;
            width: 100%;
            height: config.window.bar-height;

            HorizontalLayout {
                width: 100%;
                height: 100%;
                padding-top: 2px;
                padding-bottom: 2px;
                spacing: 4px;

                Rectangle {
                    height: 100%;
                    width: 100px;
                    elevation := Elevation {
                        border_radius: root.height / 2;
                        background: MaterialPalette.primary;
                        width: 100%;
                        height: 100%;
                    }

                    base := BaseButton {
                        text: volumeData.muted ? "muted" : volumeData.volume;
                        color: black;
                        width: 100%;
                        height: 100%;
                        clicked() => {
                            set_muted(!volumeData.muted);
                        }
                        scroll-event(event) => {
                            if event.delta_y < 0px {
                                set_volume(volumeData.volume, config.interraction.volume-scroll-step);
                            } else if event.delta_y > 0px {
                                set_volume(volumeData.volume,-config.interraction.volume-scroll-step);
                            }
                            accept
                        }
                    }
                }

                Rectangle {
                    height: 100%;
                    width: 100px;
                    Elevation {
                        border_radius: root.height / 2;
                        background: MaterialPalette.primary;
                        width: 100%;
                        height: 100%;
                    }

                    BaseButton {
                        text: brightness;
                        color: black;
                        width: 100%;
                        height: 100%;

                        scroll-event(event) => {
                            if event.delta_y < 0px {
                                set_brightness(brightness, config.interraction.brightness-scroll-step);
                            } else if event.delta_y > 0px {
                                set_brightness(brightness,-config.interraction.brightness-scroll-step);
                            }
                            accept
                        }
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                Taskbar {
                    width: 60%;
                    config: config.taskbar;
                    animation_multiplier: config.interraction.animation-multiplier;
                    workspaces: workspaces;
                    dispatch_command(cmd) => {
                        root.run_command(cmd);
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                TrayRow {
                    config: config.tray;
                    items: root.tray;
                    item_clicked(id, btn, button_x) => {
                        root.tray_item_clicked(id, btn, button_x);
                    }
                }

                FilledButton {
                    text: "Test button";
                }
            }
        }
    }

    TrayContextMenu {
        x: root.trayMenu.x-pos - self.width / 2;
        y: config.window.bar-height + 4px;
        config: config.tray;
        menu-data: root.trayMenu;
        animation_multiplier: config.interraction.animation-multiplier;
        changed height => {
            root.manage_touch("TrayMenu" ,root.trayMenu.visible, self.x, self.y, self.width, self.height);
        }
        changed x => {
            root.manage_touch("TrayMenu" ,root.trayMenu.visible, self.x, self.y, self.width, self.height);
        }

        menu_action_executed(item_id, action_id) => {
            root.menu_action_executed(item_id, action_id);
        }
    }

    Path {
        width: 10px;
        height: 10px;
        y: config.window.bar-height;
        x: window_width - self.width;
        fill: MaterialPalette.surface_container;
        fill-rule: evenodd;
        commands: "M 7 3 L 12 3 L 12 8 C 11 5 10 4 7 3";
    }

    Path {
        width: 10px;
        height: 10px;
        y: config.window.bar-height;
        x: 0px;
        fill: MaterialPalette.surface_container;
        fill-rule: evenodd;
        commands: "M 7 8 L 7 3 L 12 3 C 9 4 8 5 7 8";
    }
}
