import { Palette } from "std-widgets.slint";

import { FilledButton, Elevation } from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";

import { MaterialPalette } from "@material/material.slint";
import { MaterialScheme } from "@material/material.slint";
import { MaterialSchemes } from "@material/material.slint";
import {
    MaterialTypography,
    MaterialStyleMetrics,
} from "@material/material.slint";

import { Workspace, Taskbar } from "components/taskbar.slint";
import { TaskbarConfigSlint, ConfigSlint } from "shared-items.slint";

export struct VolumeDataSlint {
    volume: int,
    muted: bool,
}

export struct DataSlint {
    volumeData: VolumeDataSlint,
    brightness: int,
}

export component barWindow inherits Window {
    in property <[Workspace]> workspaces;
    in property <ConfigSlint> config;
    in property <DataSlint> data;
    in-out property <length> window_width <=> self.width;

    default-font-size: 10px;
    background: transparent;

    callback run_command(string);
    callback set_volume(int,int);

    Rectangle {
        x: 0px;
        y: 0px;
        background: MaterialPalette.surface_container;
        width: 100%;
        height: config.window.bar-height;

        HorizontalLayout {
            width: 100%;
            height: 100%;
            padding: 0px;
            spacing: 0px;

            Rectangle {
                height: 100%;
                width: 100px;
                elevation := Elevation {
                    border_radius: root.height / 2;
                    background: MaterialPalette.primary;
                    width: 100%;
                    height: 100%;
                }

                base := BaseButton {
                    text: data.volumeData.volume;
                    color: black;
                    width: 100%;
                    height: 100%;

                    scroll-event(event) => {
                        if event.delta_y < 0px {
                            set_volume(data.volumeData.volume, config.interraction.volume-scroll-step);
                        } else if event.delta_y > 0px {
                            set_volume(data.volumeData.volume,-config.interraction.volume-scroll-step);
                        }
                        accept
                    }

                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            Taskbar {
                width: 60%;
                height: 70%;
                icon-size: config.taskbar.icon-size;
                max-text-lenght: config.taskbar.max-text-lenght;
                workspaces: workspaces;
                dispatch_command(cmd) => {
                    root.run_command(cmd);
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            FilledButton {
                text: "Test button";
            }
        }
    }

    Path {
        width: 10px;
        height: 10px;
        y: config.window.bar-height;
        x: window_width - self.width;
        fill: MaterialPalette.surface_container;
        fill-rule: evenodd;

        commands: "M 7 3 L 12 3 L 12 8 C 11 5 10 4 7 3";
    }

    Path {
        width: 10px;
        height: 10px;
        y: config.window.bar-height;
        x: 0px;
        fill: MaterialPalette.surface_container;
        fill-rule: evenodd;

        commands: "M 7 8 L 7 3 L 12 3 C 9 4 8 5 7 8";
    }
}
