import { Palette } from "std-widgets.slint";
import { FilledButton, Elevation, MenuItem } from "@material/material.slint";
import { BaseButton } from "@material/ui/components/base_button.slint";
import {
    MaterialPalette,
    MaterialStyleMetrics,
    MaterialTypography,
} from "@material/material.slint";
import {
    TaskbarConfigSlint,
    ConfigSlint,
} from "shared-items.slint";

import { Workspace, Taskbar } from "components/taskbar.slint";
import {
    TrayRow,
    TrayContextMenu,
    TrayItemSlint,
    ContextMenuDataSlint,
} from "components/tray.slint";
import { ProfilesRow } from "components/profiles.slint";

import { MaterialStyleMetrics } from "material-1.0/material.slint";
import {
    MaterialPalette,
} from "material-1.0/ui/styling/material_palette.slint";

export struct TimeDataSlint { hour: int, minute: int }
export struct DateDataSlint { day: int, month: int, year: int }
export struct StringDateDataSlint { day: string, month: string, year: string }

export struct UpTimeSlint { hour: int, minute: int }

export component barWindow inherits Window {
    in property <[Workspace]> workspaces;
    in property <[TrayItemSlint]> tray;
    in-out property <ContextMenuDataSlint> trayMenu;

    in property <string> powerProfile;
    in property <string> fanProfile;


    in property <ConfigSlint> config;
    in-out property <length> window_width <=> self.width;
    in-out property <length> window_height <=> self.height;

    in property <[{ name: string, icon: image }]> power_profiles: [
        { name: "Power Saver", icon: @image-url("./assets/profiles/power/power_saver.svg") },
        { name: "Balanced", icon: @image-url("./assets/profiles/power/balanced.svg") },
        { name: "Performance", icon: @image-url("./assets/profiles/power/performance.svg") }
    ];

    in property <[{ name: string, icon: image }]> fan_profiles: [
        { name: "Quiet", icon: @image-url("./assets/profiles/fan/quiet.svg") },
        { name: "Balanced", icon: @image-url("./assets/profiles/fan/balanced.svg") },
        { name: "Performance", icon: @image-url("./assets/profiles/fan/performance.svg") },
        { name: "Extreme", icon: @image-url("./assets/profiles/fan/extreme.svg") }
    ];

    default-font-size: 10px;
    background: transparent;

    callback run_command(string);


    callback set_power_profile(string);
    callback set_fan_profile(string);

    callback tray_item_clicked(string, string, length);
    callback menu_action_executed(string, string);

    callback manage_touch(string, bool, length, length, length, length);

    public function init_ui() {
        trayMenu.x-pos = layRight.x;
        manage_touch("Left", true, layLeft.x, layLeft.y, layLeft.width, layLeft.height);
        manage_touch("Right", true, layRight.x, layRight.y, layRight.width, layRight.height);
        manage_touch("Taskbar", true, taskbar.x, taskbar.y, taskbar.width, taskbar.height);
    }

    property <bool> batteryPopupVis;
    property <bool> networkPopupVis;
    property <bool> bluetoothPopupVis;
    property <bool> brightnessPopupVis;
    property <bool> volumePopupVis;
    property <bool> controlPanelVis;

    layLeft := HorizontalLayout {
        y: 0px;
        x: 0px;
        width: rectLeft.preferred-width;
        height: config.window.bar-height;
        rectLeft := Rectangle {
            background: MaterialPalette.surface;
            border-bottom-right-radius: MaterialStyleMetrics.border_radius_16;

            Path {
                width: ((config.window.bar-height + 3px) - MaterialStyleMetrics.border_radius_16) + 2px;
                height: ((config.window.bar-height + 3px) - MaterialStyleMetrics.border_radius_16) + 1px;
                y: 0px;
                x: rectLeft.width - 1px;
                fill: MaterialPalette.surface;
                commands: "M 7 8 L 7 3 L 12 3 C 9 4 8 5 7 8";
            }

            HorizontalLayout {
                padding-left: 30px;
                padding-right: 30px;
                padding-top: 2px;
                padding-bottom: 2px;
                spacing: MaterialStyleMetrics.spacing_2;

                ProfilesRow {
                    set_power_profile(profile) => {
                        set_power_profile(profile);
                        if (profile == "Power Saver") {
                            root.set_fan_profile("quiet");
                        }
                        if (profile == "Balanced") {
                            root.set_fan_profile("balanced");
                        }
                        if (profile == "Performance") {
                            root.set_fan_profile("performance");
                        }
                    }
                    profiles: root.power_profiles;
                    powerProfile: powerProfile;
                }
            }
        }
    }

    layRight := HorizontalLayout {
        y: 0px;
        x: root.window_width - self.width;
        width: rectRight.preferred-width;
        height: config.window.bar-height;
        animate width {
            duration: 100ms * root.config.interaction.animation_multiplier;
            easing: ease-in-out;
        }
        rectRight := Rectangle {
            height: 100%;
            background: MaterialPalette.surface;
            border-bottom-left-radius: MaterialStyleMetrics.border_radius_16;

            Path {
                width: ((config.window.bar-height + 3px) - MaterialStyleMetrics.border_radius_16) + 2px;
                height: ((config.window.bar-height + 3px) - MaterialStyleMetrics.border_radius_16) + 1px;
                y: 0px;
                x: -self.width + 1px;
                fill: MaterialPalette.surface;
                fill-rule: evenodd;
                commands: "M 7 3 L 12 3 L 12 8 C 11 5 10 4 7 3";
            }

            HorizontalLayout {
                padding-left: 30px;
                padding-right: 30px;
                padding-top: 2px;
                padding-bottom: 2px;
                spacing: MaterialStyleMetrics.spacing_2;

                TrayRow {
                    config: config.tray;
                    items: root.tray;
                    item_clicked(id, btn, button_x) => {
                        root.tray_item_clicked(id, btn, button_x + rectRight.x + layRight.x);
                    }
                }
            }
        }
    }

    HorizontalLayout {
        x: 0px;
        y: 0px;
        alignment: center;
        taskbar := Taskbar {
            changed height => {
                manage_touch("Taskbar", true, taskbar.x, taskbar.y, taskbar.width, taskbar.height);
            }
            config: config;
            animation_multiplier: config.interaction.animation-multiplier;
            workspaces: workspaces;
            dispatch_command(cmd) => {
                root.run_command(cmd);
            }
        }
    }

    TrayContextMenu {
        x: root.trayMenu.x-pos - self.width / 2;
        y: config.window.bar-height + 4px;
        config: config.tray;
        menuData: root.trayMenu;
        animation_multiplier: config.interaction.animation-multiplier;

        menu_action_executed(item_id, action_id) => {
            root.menu_action_executed(item_id, action_id);
        }
    }

    Path {
        width: 10px;
        height: 10px;
        y: config.window.bar-height;
        x: window_width - self.width;
        fill: MaterialPalette.surface;
        fill-rule: evenodd;
        commands: "M 7 3 L 12 3 L 12 8 C 11 5 10 4 7 3";
    }

    Path {
        width: 10px;
        height: 10px;
        y: config.window.bar-height;
        x: 0px;
        fill: MaterialPalette.surface;
        fill-rule: evenodd;
        commands: "M 7 8 L 7 3 L 12 3 C 9 4 8 5 7 8";
    }
}
