import { Palette } from "std-widgets.slint";

import { FilledButton } from "@material/material.slint";
import { MaterialPalette } from "@material/material.slint";
import { MaterialScheme } from "@material/material.slint";
import { MaterialSchemes } from "@material/material.slint";
import {
    MaterialTypography,
    MaterialStyleMetrics,
} from "@material/material.slint";

import { ConfigSlint } from "shared-items.slint";

export component clipboardWindow inherits Window {
    in property <ConfigSlint> config;

    default-font-size: 10px;
    background: transparent;

    Rectangle {
        x: 0px;
        y: 0px;
        background: MaterialPalette.surface_container;
        width: 100%;
        height: 100%;
        FilledButton {
            text: "Test button";
        }
    }
}
