export struct TaskbarConfigSlint {
    icon_size: length,
    indicator_max_width: length,
    taskbar_max_width: length,
}

export struct TrayConfigSlint {
    icon_size: length,
    menu_icon_size: length,
    width: length,
    max-height: length,
}

export struct NoticificationConfigSlint {
    icon_size: length,
    notification_width: length,
    notification_max_height: length,
}


export struct WindowConfigSlint {
    bar_height: length,
}

export struct InterractionConfigSlint {
    animation_multiplier: float,
    volume_scroll_step: int,
    brightness_scroll_step: int,
}


export struct ConfigSlint {
    window: WindowConfigSlint,
    interraction: InterractionConfigSlint,
    taskbar: TaskbarConfigSlint,
    tray: TrayConfigSlint,
    notification: NoticificationConfigSlint,
}
