export struct TaskbarConfigSlint {
    icon_size: length,
    indicator_max_width: length,
    taskbar_max_width: length,
}

export struct TrayConfigSlint {
    icon_size: length,
    menu_icon_size: length,
    width: length,
    max-height: length,
}

export struct NoticificationConfigSlint {
    icon_size: length,
    notification_width: length,
    notification_max_height: length,
    other_action_buttons: bool,
}

export struct WindowConfigSlint {
    bar_height: length,
}

export struct InteractionConfigSlint {
    animation_multiplier: float,
    volume_scroll_step: int,
    brightness_scroll_step: int,
}

export struct ConfigSlint {
    hardware_specific_features:bool,
    window: WindowConfigSlint,
    interaction: InteractionConfigSlint,
    taskbar: TaskbarConfigSlint,
    tray: TrayConfigSlint,
    notification: NoticificationConfigSlint,
}
