export struct TaskbarConfigSlint {
    icon_size: length,
    indicator_max_width: length,
    taskbar_max_width: length,
}

export struct TrayConfigSlint {
    icon_size: length,
    menu_icon_size: length,
    width: length,
    max-height: length,
}

export struct NoticificationConfigSlint {
    icon_size: length,
    notification_width: length,
    notification_max_height: length,
    other_action_buttons: bool,
}

export struct WindowConfigSlint {
    bar_height: length,
    bar_popup_max_height: length,
    bar_popup_screen_padding: length,
}

export struct InteractionConfigSlint {
    animation_multiplier: float,
    volume_scroll_step: int,
    brightness_scroll_step: int,
}

export struct HardwareConfigSlint {
    hardware_specific_features: bool,
    temp_alert: int,
}

export struct CommandsConfigSlint {
    shutdown: string,
    reboot: string,
    lock: string,
    suspend: string,
}

export struct LookConfigSlint {
    callendar_start_column: int,
}


export struct ConfigSlint {
    look: LookConfigSlint,
    commands: CommandsConfigSlint,
    hardware: HardwareConfigSlint,
    window: WindowConfigSlint,
    interaction: InteractionConfigSlint,
    taskbar: TaskbarConfigSlint,
    tray: TrayConfigSlint,
    notification: NoticificationConfigSlint,
}

export struct SessionDataSlint {
    sync_brightness: bool,
    dark_mode: bool,
    caffeine: bool,
    dnd: bool,
}
