import { barWindow } from "bar-window.slint";
import { clipboardWindow } from "clipboard-window.slint";

export {barWindow}
export {clipboardWindow}

import { Palette } from "std-widgets.slint";

import { MaterialPalette } from "@material/material.slint";
import { MaterialScheme } from "@material/material.slint";
import { MaterialSchemes } from "@material/material.slint";

export { MaterialPalette }
export { MaterialScheme }
export { MaterialSchemes }
export {Palette}