use serde::{Deserialize, Serialize};
use slint::{Color, ComponentHandle};
use crate::{AppWindow, MaterialPalette, MaterialSchemes};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct MaterialScheme {
    pub primary: [u8; 3],
    pub surface_tint: [u8; 3],
    pub on_primary: [u8; 3],
    pub primary_container: [u8; 3],
    pub on_primary_container: [u8; 3],
    pub secondary: [u8; 3],
    pub on_secondary: [u8; 3],
    pub secondary_container: [u8; 3],
    pub on_secondary_container: [u8; 3],
    pub tertiary: [u8; 3],
    pub on_tertiary: [u8; 3],
    pub tertiary_container: [u8; 3],
    pub on_tertiary_container: [u8; 3],
    pub error: [u8; 3],
    pub on_error: [u8; 3],
    pub error_container: [u8; 3],
    pub on_error_container: [u8; 3],
    pub background: [u8; 3],
    pub on_background: [u8; 3],
    pub surface: [u8; 3],
    pub on_surface: [u8; 3],
    pub surface_variant: [u8; 3],
    pub on_surface_variant: [u8; 3],
    pub outline: [u8; 3],
    pub outline_variant: [u8; 3],
}

pub fn default_light_scheme() -> MaterialScheme {
    MaterialScheme {
        primary: [68, 94, 145],
        surface_tint: [68, 94, 145],
        on_primary: [255, 255, 255],
        primary_container: [216, 226, 255],
        on_primary_container: [0, 26, 66],
        secondary: [87, 94, 113],
        on_secondary: [255, 255, 255],
        secondary_container: [219, 226, 249],
        on_secondary_container: [20, 27, 44],
        tertiary: [113, 85, 115],
        on_tertiary: [255, 255, 255],
        tertiary_container: [252, 215, 251],
        on_tertiary_container: [41, 19, 45],
        error: [186, 26, 26],
        on_error: [255, 255, 255],
        error_container: [255, 218, 214],
        on_error_container: [65, 0, 2],
        background: [249, 249, 255],
        on_background: [26, 27, 32],
        surface: [249, 249, 255],
        on_surface: [26, 27, 32],
        surface_variant: [225, 226, 236],
        on_surface_variant: [68, 71, 79],
        outline: [117, 119, 127],
        outline_variant: [196, 198, 208],
    }
}

pub fn default_dark_scheme() -> MaterialScheme {
    MaterialScheme {
        primary: [173, 198, 255],
        surface_tint: [173, 198, 255],
        on_primary: [17, 47, 96],
        primary_container: [43, 70, 120],
        on_primary_container: [216, 226, 255],
        secondary: [191, 198, 220],
        on_secondary: [41, 48, 65],
        secondary_container: [63, 71, 89],
        on_secondary_container: [219, 226, 249],
        tertiary: [222, 188, 223],
        on_tertiary: [64, 40, 67],
        tertiary_container: [88, 62, 91],
        on_tertiary_container: [252, 215, 251],
        error: [255, 180, 171],
        on_error: [105, 0, 5],
        error_container: [147, 0, 10],
        on_error_container: [255, 218, 214],
        background: [17, 19, 24],
        on_background: [226, 226, 233],
        surface: [17, 19, 24],
        on_surface: [226, 226, 233],
        surface_variant: [68, 71, 79],
        on_surface_variant: [196, 198, 208],
        outline: [142, 144, 153],
        outline_variant: [68, 71, 79],
    }
}


fn rgb(c: [u8; 3]) -> Color {
    Color::from_rgb_u8(c[0], c[1], c[2])
}

pub fn apply_config_palette(ui: &AppWindow, config: &crate::config::AppConfig) {
    let palette = ui.global::<MaterialPalette>();

    let light = &config.theme.light_scheme;
    let dark = &config.theme.dark_scheme;

    let schemes = MaterialSchemes {
        light: crate::slint_generatedAppWindow::MaterialScheme {
            primary: rgb(light.primary),
            surfaceTint: rgb(light.surface_tint),
            onPrimary: rgb(light.on_primary),
            primaryContainer: rgb(light.primary_container),
            onPrimaryContainer: rgb(light.on_primary_container),
            secondary: rgb(light.secondary),
            onSecondary: rgb(light.on_secondary),
            secondaryContainer: rgb(light.secondary_container),
            onSecondaryContainer: rgb(light.on_secondary_container),
            tertiary: rgb(light.tertiary),
            onTertiary: rgb(light.on_tertiary),
            tertiaryContainer: rgb(light.tertiary_container),
            onTertiaryContainer: rgb(light.on_tertiary_container),
            error: rgb(light.error),
            onError: rgb(light.on_error),
            errorContainer: rgb(light.error_container),
            onErrorContainer: rgb(light.on_error_container),
            background: rgb(light.background),
            onBackground: rgb(light.on_background),
            surface: rgb(light.surface),
            onSurface: rgb(light.on_surface),
            surfaceVariant: rgb(light.surface_variant),
            onSurfaceVariant: rgb(light.on_surface_variant),
            outline: rgb(light.outline),
            outlineVariant: rgb(light.outline_variant),
            shadow: Color::from_rgb_u8(0, 0, 0),
            scrim: Color::from_rgb_u8(0, 0, 0),
            inverseSurface: rgb(light.surface),
            inverseOnSurface: rgb(light.on_surface),
            inversePrimary: rgb(light.primary),
            primaryFixed: rgb(light.primary_container),
            onPrimaryFixed: rgb(light.on_primary_container),
            primaryFixedDim: rgb(light.primary),
            onPrimaryFixedVariant: rgb(light.primary_container),
            secondaryFixed: rgb(light.secondary_container),
            onSecondaryFixed: rgb(light.on_secondary_container),
            secondaryFixedDim: rgb(light.secondary),
            onSecondaryFixedVariant: rgb(light.secondary_container),
            tertiaryFixed: rgb(light.tertiary_container),
            onTertiaryFixed: rgb(light.on_tertiary_container),
            tertiaryFixedDim: rgb(light.tertiary),
            onTertiaryFixedVariant: rgb(light.tertiary_container),
            surfaceDim: rgb(light.surface),
            surfaceBright: rgb(light.surface),
            surfaceContainerLowest: rgb(light.surface),
            surfaceContainerLow: rgb(light.surface),
            surfaceContainer: rgb(light.surface),
            surfaceContainerHigh: rgb(light.surface),
            surfaceContainerHighest: rgb(light.surface),
        },

        dark: crate::slint_generatedAppWindow::MaterialScheme {
            primary: rgb(dark.primary),
            surfaceTint: rgb(dark.surface_tint),
            onPrimary: rgb(dark.on_primary),
            primaryContainer: rgb(dark.primary_container),
            onPrimaryContainer: rgb(dark.on_primary_container),
            secondary: rgb(dark.secondary),
            onSecondary: rgb(dark.on_secondary),
            secondaryContainer: rgb(dark.secondary_container),
            onSecondaryContainer: rgb(dark.on_secondary_container),
            tertiary: rgb(dark.tertiary),
            onTertiary: rgb(dark.on_tertiary),
            tertiaryContainer: rgb(dark.tertiary_container),
            onTertiaryContainer: rgb(dark.on_tertiary_container),
            error: rgb(dark.error),
            onError: rgb(dark.on_error),
            errorContainer: rgb(dark.error_container),
            onErrorContainer: rgb(dark.on_error_container),
            background: rgb(dark.background),
            onBackground: rgb(dark.on_background),
            surface: rgb(dark.surface),
            onSurface: rgb(dark.on_surface),
            surfaceVariant: rgb(dark.surface_variant),
            onSurfaceVariant: rgb(dark.on_surface_variant),
            outline: rgb(dark.outline),
            outlineVariant: rgb(dark.outline_variant),
            shadow: Color::from_rgb_u8(0, 0, 0),
            scrim: Color::from_rgb_u8(0, 0, 0),
            inverseSurface: rgb(dark.surface),
            inverseOnSurface: rgb(dark.on_surface),
            inversePrimary: rgb(dark.primary),
            primaryFixed: rgb(dark.primary_container),
            onPrimaryFixed: rgb(dark.on_primary_container),
            primaryFixedDim: rgb(dark.primary),
            onPrimaryFixedVariant: rgb(dark.primary_container),
            secondaryFixed: rgb(dark.secondary_container),
            onSecondaryFixed: rgb(dark.on_secondary_container),
            secondaryFixedDim: rgb(dark.secondary),
            onSecondaryFixedVariant: rgb(dark.secondary_container),
            tertiaryFixed: rgb(dark.tertiary_container),
            onTertiaryFixed: rgb(dark.on_tertiary_container),
            tertiaryFixedDim: rgb(dark.tertiary),
            onTertiaryFixedVariant: rgb(dark.tertiary_container),
            surfaceDim: rgb(dark.surface),
            surfaceBright: rgb(dark.surface),
            surfaceContainerLowest: rgb(dark.surface),
            surfaceContainerLow: rgb(dark.surface),
            surfaceContainer: rgb(dark.surface),
            surfaceContainerHigh: rgb(dark.surface),
            surfaceContainerHighest: rgb(dark.surface),
        },
    };

    palette.set_schemes(schemes);
}