use serde::{Deserialize, Serialize};
use slint::{Color};
use crate::{MaterialSchemes};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct MaterialScheme {
    pub primary: [u8; 3],
    pub surface_tint: [u8; 3],
    pub on_primary: [u8; 3],
    pub primary_container: [u8; 3],
    pub on_primary_container: [u8; 3],
    pub secondary: [u8; 3],
    pub on_secondary: [u8; 3],
    pub secondary_container: [u8; 3],
    pub on_secondary_container: [u8; 3],
    pub tertiary: [u8; 3],
    pub on_tertiary: [u8; 3],
    pub tertiary_container: [u8; 3],
    pub on_tertiary_container: [u8; 3],
    pub error: [u8; 3],
    pub on_error: [u8; 3],
    pub error_container: [u8; 3],
    pub on_error_container: [u8; 3],
    pub background: [u8; 3],
    pub on_background: [u8; 3],
    pub surface: [u8; 3],
    pub on_surface: [u8; 3],
    pub surface_variant: [u8; 3],
    pub on_surface_variant: [u8; 3],
    pub outline: [u8; 3],
    pub outline_variant: [u8; 3],
    pub shadow: [u8; 3],
    pub scrim: [u8; 3],
    pub inverse_surface: [u8; 3],
    pub inverse_on_surface: [u8; 3],
    pub inverse_primary: [u8; 3],
    pub primary_fixed: [u8; 3],
    pub on_primary_fixed: [u8; 3],
    pub primary_fixed_dim: [u8; 3],
    pub on_primary_fixed_variant: [u8; 3],
    pub secondary_fixed: [u8; 3],
    pub on_secondary_fixed: [u8; 3],
    pub secondary_fixed_dim: [u8; 3],
    pub on_secondary_fixed_variant: [u8; 3],
    pub tertiary_fixed: [u8; 3],
    pub on_tertiary_fixed: [u8; 3],
    pub tertiary_fixed_dim: [u8; 3],
    pub on_tertiary_fixed_variant: [u8; 3],
    pub surface_dim: [u8; 3],
    pub surface_bright: [u8; 3],
    pub surface_container_lowest: [u8; 3],
    pub surface_container_low: [u8; 3],
    pub surface_container: [u8; 3],
    pub surface_container_high: [u8; 3],
    pub surface_container_highest: [u8; 3],
}

pub fn default_light_scheme() -> MaterialScheme {
    MaterialScheme {
        primary: [68, 94, 145],
        surface_tint: [68, 94, 145],
        on_primary: [255, 255, 255],
        primary_container: [216, 226, 255],
        on_primary_container: [0, 26, 66],
        secondary: [87, 94, 113],
        on_secondary: [255, 255, 255],
        secondary_container: [219, 226, 249],
        on_secondary_container: [20, 27, 44],
        tertiary: [113, 85, 115],
        on_tertiary: [255, 255, 255],
        tertiary_container: [252, 215, 251],
        on_tertiary_container: [41, 19, 45],
        error: [186, 26, 26],
        on_error: [255, 255, 255],
        error_container: [255, 218, 214],
        on_error_container: [65, 0, 2],
        background: [249, 249, 255],
        on_background: [26, 27, 32],
        surface: [249, 249, 255],
        on_surface: [26, 27, 32],
        surface_variant: [225, 226, 236],
        on_surface_variant: [68, 71, 79],
        outline: [117, 119, 127],
        outline_variant: [196, 198, 208],
        shadow: [0, 0, 0],
        scrim: [0, 0, 0],
        inverse_surface: [47, 48, 54],
        inverse_on_surface: [240, 240, 247],
        inverse_primary: [173, 198, 255],
        primary_fixed: [216, 226, 255],
        on_primary_fixed: [0, 26, 66],
        primary_fixed_dim: [173, 198, 255],
        on_primary_fixed_variant: [43, 70, 120],
        secondary_fixed: [219, 226, 249],
        on_secondary_fixed: [20, 27, 44],
        secondary_fixed_dim: [191, 198, 220],
        on_secondary_fixed_variant: [63, 71, 89],
        tertiary_fixed: [252, 215, 251],
        on_tertiary_fixed: [41, 19, 45],
        tertiary_fixed_dim: [222, 188, 223],
        on_tertiary_fixed_variant: [88, 62, 91],
        surface_dim: [217, 217, 224],
        surface_bright: [246, 246, 255],
        surface_container_lowest: [255, 255, 255],
        surface_container_low: [243, 243, 250],
        surface_container: [238, 237, 244],
        surface_container_high: [232, 231, 239],
        surface_container_highest: [226, 226, 233],
    }
}

pub fn default_dark_scheme() -> MaterialScheme {
    MaterialScheme {
        primary: [173, 198, 255],
        surface_tint: [173, 198, 255],
        on_primary: [17, 47, 96],
        primary_container: [43, 70, 120],
        on_primary_container: [216, 226, 255],
        secondary: [191, 198, 220],
        on_secondary: [41, 48, 65],
        secondary_container: [63, 71, 89],
        on_secondary_container: [219, 226, 249],
        tertiary: [222, 188, 223],
        on_tertiary: [64, 40, 67],
        tertiary_container: [88, 62, 91],
        on_tertiary_container: [252, 215, 251],
        error: [255, 180, 171],
        on_error: [105, 0, 5],
        error_container: [147, 0, 10],
        on_error_container: [255, 218, 214],
        background: [17, 19, 24],
        on_background: [226, 226, 233],
        surface: [17, 19, 24],
        on_surface: [226, 226, 233],
        surface_variant: [68, 71, 79],
        on_surface_variant: [196, 198, 208],
        outline: [142, 144, 153],
        outline_variant: [68, 71, 79],
        shadow: [0, 0, 0],
        scrim: [0, 0, 0],
        inverse_surface: [226, 226, 233],
        inverse_on_surface: [47, 48, 54],
        inverse_primary: [68, 94, 145],
        primary_fixed: [216, 226, 255],
        on_primary_fixed: [0, 26, 66],
        primary_fixed_dim: [173, 198, 255],
        on_primary_fixed_variant: [43, 70, 120],
        secondary_fixed: [219, 226, 249],
        on_secondary_fixed: [20, 27, 44],
        secondary_fixed_dim: [191, 198, 220],
        on_secondary_fixed_variant: [63, 71, 89],
        tertiary_fixed: [252, 215, 251],
        on_tertiary_fixed: [41, 19, 45],
        tertiary_fixed_dim: [222, 188, 223],
        on_tertiary_fixed_variant: [88, 62, 91],
        surface_dim: [17, 19, 24],
        surface_bright: [55, 57, 62],
        surface_container_lowest: [12, 14, 19],
        surface_container_low: [26, 27, 32],
        surface_container: [30, 31, 37],
        surface_container_high: [40, 42, 47],
        surface_container_highest: [51, 53, 58],
    }
}

fn rgb(c: [u8; 3]) -> Color {
    Color::from_rgb_u8(c[0], c[1], c[2])
}

pub fn build_config_palette(
    config: &crate::config::AppConfig,
) -> MaterialSchemes {
    let light = &config.theme.light_scheme;
    let dark = &config.theme.dark_scheme;

    MaterialSchemes {
        light: crate::MaterialScheme {
            primary: rgb(light.primary),
            surfaceTint: rgb(light.surface_tint),
            onPrimary: rgb(light.on_primary),
            primaryContainer: rgb(light.primary_container),
            onPrimaryContainer: rgb(light.on_primary_container),
            secondary: rgb(light.secondary),
            onSecondary: rgb(light.on_secondary),
            secondaryContainer: rgb(light.secondary_container),
            onSecondaryContainer: rgb(light.on_secondary_container),
            tertiary: rgb(light.tertiary),
            onTertiary: rgb(light.on_tertiary),
            tertiaryContainer: rgb(light.tertiary_container),
            onTertiaryContainer: rgb(light.on_tertiary_container),
            error: rgb(light.error),
            onError: rgb(light.on_error),
            errorContainer: rgb(light.error_container),
            onErrorContainer: rgb(light.on_error_container),
            background: rgb(light.background),
            onBackground: rgb(light.on_background),
            surface: rgb(light.surface),
            onSurface: rgb(light.on_surface),
            surfaceVariant: rgb(light.surface_variant),
            onSurfaceVariant: rgb(light.on_surface_variant),
            outline: rgb(light.outline),
            outlineVariant: rgb(light.outline_variant),
            shadow: rgb(light.shadow),
            scrim: rgb(light.scrim),
            inverseSurface: rgb(light.inverse_surface),
            inverseOnSurface: rgb(light.inverse_on_surface),
            inversePrimary: rgb(light.inverse_primary),
            primaryFixed: rgb(light.primary_fixed),
            onPrimaryFixed: rgb(light.on_primary_fixed),
            primaryFixedDim: rgb(light.primary_fixed_dim),
            onPrimaryFixedVariant: rgb(light.on_primary_fixed_variant),
            secondaryFixed: rgb(light.secondary_fixed),
            onSecondaryFixed: rgb(light.on_secondary_fixed),
            secondaryFixedDim: rgb(light.secondary_fixed_dim),
            onSecondaryFixedVariant: rgb(light.on_secondary_fixed_variant),
            tertiaryFixed: rgb(light.tertiary_fixed),
            onTertiaryFixed: rgb(light.on_tertiary_fixed),
            tertiaryFixedDim: rgb(light.tertiary_fixed_dim),
            onTertiaryFixedVariant: rgb(light.on_tertiary_fixed_variant),
            surfaceDim: rgb(light.surface_dim),
            surfaceBright: rgb(light.surface_bright),
            surfaceContainerLowest: rgb(light.surface_container_lowest),
            surfaceContainerLow: rgb(light.surface_container_low),
            surfaceContainer: rgb(light.surface_container),
            surfaceContainerHigh: rgb(light.surface_container_high),
            surfaceContainerHighest: rgb(light.surface_container_highest),
        },

        dark: crate::MaterialScheme {
            primary: rgb(dark.primary),
            surfaceTint: rgb(dark.surface_tint),
            onPrimary: rgb(dark.on_primary),
            primaryContainer: rgb(dark.primary_container),
            onPrimaryContainer: rgb(dark.on_primary_container),
            secondary: rgb(dark.secondary),
            onSecondary: rgb(dark.on_secondary),
            secondaryContainer: rgb(dark.secondary_container),
            onSecondaryContainer: rgb(dark.on_secondary_container),
            tertiary: rgb(dark.tertiary),
            onTertiary: rgb(dark.on_tertiary),
            tertiaryContainer: rgb(dark.tertiary_container),
            onTertiaryContainer: rgb(dark.on_tertiary_container),
            error: rgb(dark.error),
            onError: rgb(dark.on_error),
            errorContainer: rgb(dark.error_container),
            onErrorContainer: rgb(dark.on_error_container),
            background: rgb(dark.background),
            onBackground: rgb(dark.on_background),
            surface: rgb(dark.surface),
            onSurface: rgb(dark.on_surface),
            surfaceVariant: rgb(dark.surface_variant),
            onSurfaceVariant: rgb(dark.on_surface_variant),
            outline: rgb(dark.outline),
            outlineVariant: rgb(dark.outline_variant),
            shadow: rgb(dark.shadow),
            scrim: rgb(dark.scrim),
            inverseSurface: rgb(dark.inverse_surface),
            inverseOnSurface: rgb(dark.inverse_on_surface),
            inversePrimary: rgb(dark.inverse_primary),
            primaryFixed: rgb(dark.primary_fixed),
            onPrimaryFixed: rgb(dark.on_primary_fixed),
            primaryFixedDim: rgb(dark.primary_fixed_dim),
            onPrimaryFixedVariant: rgb(dark.on_primary_fixed_variant),
            secondaryFixed: rgb(dark.secondary_fixed),
            onSecondaryFixed: rgb(dark.on_secondary_fixed),
            secondaryFixedDim: rgb(dark.secondary_fixed_dim),
            onSecondaryFixedVariant: rgb(dark.on_secondary_fixed_variant),
            tertiaryFixed: rgb(dark.tertiary_fixed),
            onTertiaryFixed: rgb(dark.on_tertiary_fixed),
            tertiaryFixedDim: rgb(dark.tertiary_fixed_dim),
            onTertiaryFixedVariant: rgb(dark.on_tertiary_fixed_variant),
            surfaceDim: rgb(dark.surface_dim),
            surfaceBright: rgb(dark.surface_bright),
            surfaceContainerLowest: rgb(dark.surface_container_lowest),
            surfaceContainerLow: rgb(dark.surface_container_low),
            surfaceContainer: rgb(dark.surface_container),
            surfaceContainerHigh: rgb(dark.surface_container_high),
            surfaceContainerHighest: rgb(dark.surface_container_highest),
        },
    }
}